---
title: "table 1"
author: "Sarah Opie-Martin"
date: "2025-02-26"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)


source("~/casual/preamble.R")

set_flextable_defaults(
  font.size = 12, font.family = "Open Sans",
  font.color = "#333333",
  table.layout = "fixed",
  border.color = "gray",
  padding.top = 3, padding.bottom = 3,
  padding.left = 4, padding.right = 4
)


baseline <- readRDS("cleaned_data/baseline_data.rds")

matched_data <- readRDS("matched_data_noPMS.rds")

# Changes here due to going from bool to numeric
matched_ids <- matched_data %>%
  mutate(status = case_when(
    treated == 1 ~ "Treated",
    TRUE ~ "Matched control"
  )) %>%
  dplyr::select(PRACTICE_CODE, status)

outcomes_2024 <- readRDS("cleaned_data/outcomes_2024.rds")

# Changes here due to going from bool to numeric
baseline <- baseline %>%
  left_join(matched_ids, by = "PRACTICE_CODE") %>%
  left_join(outcomes_2024, by = "PRACTICE_CODE") %>%
  filter((LLR == "LLR" & treated == TRUE) | (LLR == "Not LLR" & treated == FALSE)) %>%
  filter(contract_type != "PMS") %>%
  mutate(
    IMD_quintile_fct = as.factor(clean_quintile),
    status = case_when(
      treated == 1 & status == "Treated" ~ "Treated",
      treated == 1 & is.na(status) ~ "Treated excl",
      treated == 0 & status == "Matched control" ~ "Matched control",
      treated == 0 & is.na(status) ~ "Unmatched control"
    ),
    status = factor(status, levels = c("Treated", "Matched control", "Unmatched control", "Treated excl"))
  ) %>%
  mutate(
    across(c(q18_12pct, q28_12pct, q90_12pct), ~ . * 100)
  )

tx_excl <- baseline %>%
  filter(status == "Treated excl") %>%
  dplyr::select(PRACTICE_CODE)
tx <- baseline %>%
  filter(status == "Treated") %>%
  dplyr::select(PRACTICE_CODE)
```

## Table 1


```{r overall_t1}
print("### Mean demographics treated V matched control V potential controls (May 2021)")
print("N.B. Here 1 is most deprived IMD fifth, 5 is least deprived")
# strata <- c(list(Total = baseline), split(baseline, baseline$LLR_not_ROE))
labels <- list(
  variables = list(
    NUMBER_OF_PATIENTS = "List size", # in
    PERC_MALE = "Percentage of registered patients are male", # in
    PERC_65 = "Percentage of registered patients are >65 years old", # in
    IMD_quintile_fct = "IMD quintile based on registered patient place of residence", # in
    POP_RURAL = "Percentage of registered patients living in rural areas", # in
    POP_WHITE = "Percentage of white people living in LSOAs on registered patients", # in
    POP_ENG2 = "Percentage of people with English as a second language living in LSOAs on registered patients", # in
    chi = "Carr-Hill Index", # in
    total_gp_extg_fte_weighted = "FTE GPs (excluding training grade) per 1000 weighted patients", # in
    # total_gp_extg_fte_weighted_POST_INT = "fte gps post intervention",
    total_nurses_fte_weighted = "FTE nurses per 1000 weighted patients", # in
    # total_nurses_fte_weighted_POST_INT = "fte nurses post intervention",
    total_admin_fte_weighted = "FTE admin per 1000 weighted patients", # in
    # total_admin_fte_weighted_POST_INT = "total admin post intervention",
    gp_partner_1 = "Single partner practices",
    contract_type = "Contract type",
    q18_12pct = "Percentage of respondents reporting good overall experience of booking an appointment", # in
    # q18_12pct_POST_INT = "Overall experience booking post intervention",
    q28_12pct = "Percentage of respondents reporting good overall experience of their GP practice", # in
    # q28_12pct_POST_INT = "Overall experience post intervention",
    q90_12pct = "Percentage of respondents reporting yes overall to whether their needs were met at their last appointment", # in
    # q90_12pct_POST_INT = "Needs met post intervention",
    qof_percent = "Percentage of total QOF points achieved", # in
    # qof_percent_POST_INT = "qof points post intervention",
    AST = "Prevalence of asthma", # in
    CKD = "Prevalence of chronic kidney disease", # in
    COPD = "Prevalence of chronic obstructive pulmonary disease", # in
    CHD = "Prevalence of coronary heart disease", # in
    DM = "Prevalence of diabetes mellitus", # in
    HYP = "Prevalence of hypertension" # in
  )
)



# my.render.cont <- function(x) {
#   with(stats.apply.rounding(stats.default(x), digits = 2),
#        c("", "Mean (SD)" =sprintf("%s(&plusmn; %s)", MEAN, SD)))
# }
#
# my.render.cat <- function(x) {
#   c("", sapply(stats.default(x), function(y) with(y, sprintf("%d (%0.0f %%)", FREQ, PCT))))
# }

# table_1 <- table1(strata, labels)

# , render.continuous = my.render.cont, render.categorical=my.render.cat)

# t1flex(table_1, tablefn = "flextable")
```

``` {r subgroup_t1}
strata_sub <- c(list(Total = baseline), split(baseline, baseline$status))

table_1_sub <- table1(strata_sub, labels)

t1flex(table_1_sub, tablefn = "flextable")
```


``` {r boxplots}
baseline_long <- baseline %>%
  dplyr::select(status, q18_12pct_POST_INT, q28_12pct_POST_INT, q90_12pct_POST_INT, qof_percent_POST_INT, total_gp_extg_fte_weighted_POST_INT, total_nurses_fte_weighted_POST_INT, total_admin_fte_weighted_POST_INT) %>%
  pivot_longer(-status, names_to = "variable", values_to = "value")

ggplot(data = baseline_long %>% filter(status %in% c("Treated", "Matched control")), aes(x = status, y = value)) +
  geom_boxplot() +
  facet_wrap(. ~ variable, scales = "free")
```

``` {r distributions}
baseline_long <- baseline %>%
  dplyr::select(status, q18_12pct_POST_INT, q28_12pct_POST_INT, q90_12pct_POST_INT, qof_percent_POST_INT, total_gp_extg_fte_weighted_POST_INT, total_nurses_fte_weighted_POST_INT, total_admin_fte_weighted_POST_INT) %>%
  pivot_longer(-status, names_to = "variable", values_to = "value")

ggplot(data = baseline_long %>% filter(status %in% c("Treated", "Matched control")), aes(x = value)) +
  geom_density() +
  facet_wrap(variable ~ ., scales = "free")
```
